# Course: CS 100 Summer 2012
#
# First Name: Sam
# Last Name: Lee
# Course username: slee103
# email address: slee103@ucr.edu
#
# Lecture Section: 201
# Lab Section: 221
# TA: Wojciech Karas
#
# Assignment: assn1
#
# I hereby certify that the code in this file
# is ENTIRELY my own original work.
#
# =================================================================
CXX=g++
CXXFLAGS= -g -W -Wall -Werror -pedantic -ansi

all: main.cc
	$(CXX) $(CXXFLAGS) main.cc -o myls

clean:
	rm -f *~ myls
